// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dltphexvehvtwfukjrnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsdHBoZXh2ZWh2dHdmdWtqcm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjI1MTYsImV4cCI6MjA2OTUzODUxNn0.xod3HFrvbYwj8HxLYm7ls9Ps11sg9GcK3v0F4YzM4AA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});